### PR TITLE
add nvidia-docker slides

### PR DESCRIPTION
**Pull request by johnphho**
I left out the demo code, may add it later on.

### CODE REVIEW

**Review by EtienneDufresne — APPROVED** [review]
LGTM, looking forward to the presentation!

**Comment by hairyhenderson** [comment]
LGTM! Thanks @johnphho :)

Do you want me to merge it now, or do you want to add demo code first?

**Comment by johnphho** [comment]
I forgot to put my name on the slides.  I got the demos working afterwards.  There was an issue with the same named docker container running.  I'm going to put links in the presentation to my repo, it's easier that way.  If I do another presentation on docker I'll bring an adapter.

**Comment by hairyhenderson** [comment]
@johnphho - I'm going to merge this now - just issue a follow-up PR if there are any  changes you want to make :)

**Pull request merged**
